// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext,
} from "@graphprotocol/graph-ts";

export class LoanManager extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("LoanManager", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "LoanManager",
      [address.toHex()],
      context,
    );
  }
}

export class PoolConfigurator extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("PoolConfigurator", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "PoolConfigurator",
      [address.toHex()],
      context,
    );
  }
}

export class Pool extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Pool", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext("Pool", [address.toHex()], context);
  }
}

export class WithdrawalManager extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("WithdrawalManager", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "WithdrawalManager",
      [address.toHex()],
      context,
    );
  }
}
