// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class AddressSet extends ethereum.Event {
  get params(): AddressSet__Params {
    return new AddressSet__Params(this);
  }
}

export class AddressSet__Params {
  _event: AddressSet;

  constructor(event: AddressSet) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get oldAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get newAddress(): Address {
    return this._event.parameters[2].value.toAddress();
  }
}

export class AddressSetAsProxy extends ethereum.Event {
  get params(): AddressSetAsProxy__Params {
    return new AddressSetAsProxy__Params(this);
  }
}

export class AddressSetAsProxy__Params {
  _event: AddressSetAsProxy;

  constructor(event: AddressSetAsProxy) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get proxyAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get oldImplementationAddress(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get newImplementationAddress(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class IsleGlobalsUpdated extends ethereum.Event {
  get params(): IsleGlobalsUpdated__Params {
    return new IsleGlobalsUpdated__Params(this);
  }
}

export class IsleGlobalsUpdated__Params {
  _event: IsleGlobalsUpdated;

  constructor(event: IsleGlobalsUpdated) {
    this._event = event;
  }

  get oldAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class LoanManagerUpdated extends ethereum.Event {
  get params(): LoanManagerUpdated__Params {
    return new LoanManagerUpdated__Params(this);
  }
}

export class LoanManagerUpdated__Params {
  _event: LoanManagerUpdated;

  constructor(event: LoanManagerUpdated) {
    this._event = event;
  }

  get oldAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class MarketIdSet extends ethereum.Event {
  get params(): MarketIdSet__Params {
    return new MarketIdSet__Params(this);
  }
}

export class MarketIdSet__Params {
  _event: MarketIdSet;

  constructor(event: MarketIdSet) {
    this._event = event;
  }

  get oldMarketId(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get newMarketId(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }
}

export class PoolConfiguratorUpdated extends ethereum.Event {
  get params(): PoolConfiguratorUpdated__Params {
    return new PoolConfiguratorUpdated__Params(this);
  }
}

export class PoolConfiguratorUpdated__Params {
  _event: PoolConfiguratorUpdated;

  constructor(event: PoolConfiguratorUpdated) {
    this._event = event;
  }

  get oldAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class ProxyCreated extends ethereum.Event {
  get params(): ProxyCreated__Params {
    return new ProxyCreated__Params(this);
  }
}

export class ProxyCreated__Params {
  _event: ProxyCreated;

  constructor(event: ProxyCreated) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get proxyAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get implementationAddress(): Address {
    return this._event.parameters[2].value.toAddress();
  }
}

export class WithdrawalManagerUpdated extends ethereum.Event {
  get params(): WithdrawalManagerUpdated__Params {
    return new WithdrawalManagerUpdated__Params(this);
  }
}

export class WithdrawalManagerUpdated__Params {
  _event: WithdrawalManagerUpdated;

  constructor(event: WithdrawalManagerUpdated) {
    this._event = event;
  }

  get oldAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class PoolAddressesProvider extends ethereum.SmartContract {
  static bind(address: Address): PoolAddressesProvider {
    return new PoolAddressesProvider("PoolAddressesProvider", address);
  }

  getAddress(id: Bytes): Address {
    let result = super.call("getAddress", "getAddress(bytes32):(address)", [
      ethereum.Value.fromFixedBytes(id),
    ]);

    return result[0].toAddress();
  }

  try_getAddress(id: Bytes): ethereum.CallResult<Address> {
    let result = super.tryCall("getAddress", "getAddress(bytes32):(address)", [
      ethereum.Value.fromFixedBytes(id),
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getIsleGlobals(): Address {
    let result = super.call("getIsleGlobals", "getIsleGlobals():(address)", []);

    return result[0].toAddress();
  }

  try_getIsleGlobals(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getIsleGlobals",
      "getIsleGlobals():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getLoanManager(): Address {
    let result = super.call("getLoanManager", "getLoanManager():(address)", []);

    return result[0].toAddress();
  }

  try_getLoanManager(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getLoanManager",
      "getLoanManager():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getMarketId(): string {
    let result = super.call("getMarketId", "getMarketId():(string)", []);

    return result[0].toString();
  }

  try_getMarketId(): ethereum.CallResult<string> {
    let result = super.tryCall("getMarketId", "getMarketId():(string)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  getPoolConfigurator(): Address {
    let result = super.call(
      "getPoolConfigurator",
      "getPoolConfigurator():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_getPoolConfigurator(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getPoolConfigurator",
      "getPoolConfigurator():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getWithdrawalManager(): Address {
    let result = super.call(
      "getWithdrawalManager",
      "getWithdrawalManager():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_getWithdrawalManager(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getWithdrawalManager",
      "getWithdrawalManager():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get marketId_(): string {
    return this._call.inputValues[0].value.toString();
  }

  get globals_(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class SetAddressCall extends ethereum.Call {
  get inputs(): SetAddressCall__Inputs {
    return new SetAddressCall__Inputs(this);
  }

  get outputs(): SetAddressCall__Outputs {
    return new SetAddressCall__Outputs(this);
  }
}

export class SetAddressCall__Inputs {
  _call: SetAddressCall;

  constructor(call: SetAddressCall) {
    this._call = call;
  }

  get id(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get newAddress(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class SetAddressCall__Outputs {
  _call: SetAddressCall;

  constructor(call: SetAddressCall) {
    this._call = call;
  }
}

export class SetAddressAsProxyCall extends ethereum.Call {
  get inputs(): SetAddressAsProxyCall__Inputs {
    return new SetAddressAsProxyCall__Inputs(this);
  }

  get outputs(): SetAddressAsProxyCall__Outputs {
    return new SetAddressAsProxyCall__Outputs(this);
  }
}

export class SetAddressAsProxyCall__Inputs {
  _call: SetAddressAsProxyCall;

  constructor(call: SetAddressAsProxyCall) {
    this._call = call;
  }

  get id(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get newImplementationAddress(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get params(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }
}

export class SetAddressAsProxyCall__Outputs {
  _call: SetAddressAsProxyCall;

  constructor(call: SetAddressAsProxyCall) {
    this._call = call;
  }
}

export class SetIsleGlobalsCall extends ethereum.Call {
  get inputs(): SetIsleGlobalsCall__Inputs {
    return new SetIsleGlobalsCall__Inputs(this);
  }

  get outputs(): SetIsleGlobalsCall__Outputs {
    return new SetIsleGlobalsCall__Outputs(this);
  }
}

export class SetIsleGlobalsCall__Inputs {
  _call: SetIsleGlobalsCall;

  constructor(call: SetIsleGlobalsCall) {
    this._call = call;
  }

  get newIsleGlobals(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetIsleGlobalsCall__Outputs {
  _call: SetIsleGlobalsCall;

  constructor(call: SetIsleGlobalsCall) {
    this._call = call;
  }
}

export class SetLoanManagerImplCall extends ethereum.Call {
  get inputs(): SetLoanManagerImplCall__Inputs {
    return new SetLoanManagerImplCall__Inputs(this);
  }

  get outputs(): SetLoanManagerImplCall__Outputs {
    return new SetLoanManagerImplCall__Outputs(this);
  }
}

export class SetLoanManagerImplCall__Inputs {
  _call: SetLoanManagerImplCall;

  constructor(call: SetLoanManagerImplCall) {
    this._call = call;
  }

  get newLoanManagerImpl(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetLoanManagerImplCall__Outputs {
  _call: SetLoanManagerImplCall;

  constructor(call: SetLoanManagerImplCall) {
    this._call = call;
  }
}

export class SetMarketIdCall extends ethereum.Call {
  get inputs(): SetMarketIdCall__Inputs {
    return new SetMarketIdCall__Inputs(this);
  }

  get outputs(): SetMarketIdCall__Outputs {
    return new SetMarketIdCall__Outputs(this);
  }
}

export class SetMarketIdCall__Inputs {
  _call: SetMarketIdCall;

  constructor(call: SetMarketIdCall) {
    this._call = call;
  }

  get newMarketId_(): string {
    return this._call.inputValues[0].value.toString();
  }
}

export class SetMarketIdCall__Outputs {
  _call: SetMarketIdCall;

  constructor(call: SetMarketIdCall) {
    this._call = call;
  }
}

export class SetPoolConfiguratorImplCall extends ethereum.Call {
  get inputs(): SetPoolConfiguratorImplCall__Inputs {
    return new SetPoolConfiguratorImplCall__Inputs(this);
  }

  get outputs(): SetPoolConfiguratorImplCall__Outputs {
    return new SetPoolConfiguratorImplCall__Outputs(this);
  }
}

export class SetPoolConfiguratorImplCall__Inputs {
  _call: SetPoolConfiguratorImplCall;

  constructor(call: SetPoolConfiguratorImplCall) {
    this._call = call;
  }

  get newPoolConfiguratorImpl(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get params(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class SetPoolConfiguratorImplCall__Outputs {
  _call: SetPoolConfiguratorImplCall;

  constructor(call: SetPoolConfiguratorImplCall) {
    this._call = call;
  }
}

export class SetWithdrawalManagerImplCall extends ethereum.Call {
  get inputs(): SetWithdrawalManagerImplCall__Inputs {
    return new SetWithdrawalManagerImplCall__Inputs(this);
  }

  get outputs(): SetWithdrawalManagerImplCall__Outputs {
    return new SetWithdrawalManagerImplCall__Outputs(this);
  }
}

export class SetWithdrawalManagerImplCall__Inputs {
  _call: SetWithdrawalManagerImplCall;

  constructor(call: SetWithdrawalManagerImplCall) {
    this._call = call;
  }

  get newWithdrawalManagerImpl(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get params(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class SetWithdrawalManagerImplCall__Outputs {
  _call: SetWithdrawalManagerImplCall;

  constructor(call: SetWithdrawalManagerImplCall) {
    this._call = call;
  }
}
